FROM cypress/browsers:node16.14.0-chrome99-ff97
WORKDIR /app

COPY ./e2e-tests/package*json .

RUN npm install

COPY ./e2e-tests/cypress.config.js .
COPY ./e2e-tests/cypress ./cypress

# Put container in idle state
CMD tail -f /dev/null