version: '3'

services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - 5201:5201
    environment:
      - ASPNETCORE_ENVIRONMENT=E2E
      - ASPNETCORE_URLS=http://+:5201
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=SuperSecret123
