name: Run E2E Tests

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Using Docker Compose
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.2.6
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile.*') }}

      - name: Start containers
        run: docker-compose up -d --build

      - name: Execute tests
        run: sh ./ci-run.sh

      - name: Stop containers
        if: always()
        run: docker-compose down
